[package]
name = "cardano-ouroboros-network"
license = "GPL-3.0 OR LGPL-3.0-only"
version = "0.0.1-dev"
authors = [
  "Mark Stopka <mark.stopka@perlur.cloud>",
  "Pavel Šimerda <pavel.simerda@perlur.cloud>"
]
edition = "2018"
readme = "README.md"
repository = "https://github.com/2nd-Layer/rust-cardano-ouroboros-network/"
categories = ["network-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
